### ISSUE TITLE
Does it supports tcp/udp connection?

### ISSUE THREAD

**Issue by opensesamedoors** [carloslack/KoviD#41]

**Comment by carloslack** [comment]
I am not sure about your question, `KoviD` provides 4 connect-back ways, all of them are connection-oriented TCP.  The client script sends crafted TCP packets to the host `KoviD` is running and then if there is a match the rk will connect back to sender's

`KoviD` could accept UDP packets from the client script, I just simply chose not to, but for no particular reason.

Does it help?

**Comment by carloslack** [comment]
Closing this. If we need follow up, please open a discussion in Discussion tab
thanks
