### ISSUE TITLE
could not insert module kovid.ko: Bad address

### ISSUE THREAD

**Issue by SaigyoujiYuyuko233** [carloslack/KoviD#88]
**Describe the bug**
After ``make all``, the kernel module failed to load with error ``could not insert module kovid.ko: Bad address``.

**To Reproduce**
1. Pull the git repo, with branch ``master``
2. ``cd KoviD``
3. ``make all``
4. ``git submodule update --init volundr``
5. ``make -C volundr``
6. ``insmod ./kovid.ko``
7. See the error

**Expected behavior**
``kovid.ko`` loaded into kernel.

**Screenshots**
![image](https://github.com/carloslack/KoviD/assets/39913604/f1022b44-978e-4a29-96b0-a213f4e2a8b3)

**Desktop (please complete the following information):**
```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
GNU ld (GNU Binutils for Ubuntu) 2.38
Linux test3x 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Additional context**
I tried branches such as ``kvv1.0`` and ``kvdev``, and they all failed duing ``make``

Any help would be appreciated!

**Comment by SaigyoujiYuyuko233** [comment]
After checking out ``a6f38f9b4a92dd43d78415796c034b54237049a1``, it works.
But after ``29a32a7d9a00b06e7141fe0311926b651ff92b1b``, the issue start appearing

**Comment by carloslack** [comment]
![Screenshot from 2024-04-29 13-45-55](https://github.com/carloslack/KoviD/assets/3598702/1663bde5-07f5-4da7-8048-471d099757fb)

It works for me. Please show your `dmesg` output after running `insmod`

**Comment by SaigyoujiYuyuko233** [comment]
> ![Screenshot from 2024-04-29 13-45-55](https://private-user-images.githubusercontent.com/3598702/326440772-1663bde5-07f5-4da7-8048-471d099757fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0Nzc0NTQsIm5iZiI6MTcxNDQ3NzE1NCwicGF0aCI6Ii8zNTk4NzAyLzMyNjQ0MDc3Mi0xNjYzYmRlNS0wN2Y1LTRkYTctODA0OC00NzFkMDk5NzU3ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MzBUMTEzOTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MyNzdmMzFjOTE4MTU5YjA4Njk4NTFjMDc0NDM2YzQ1MTg5YWJlMmM3ZjM5OTEwNmY5NjJjY2MyZDk1MjcwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JUl_9ADBKgR7sKR5QzC7_jFLWiZRuUVeYk7J0sOFBKI)
> 
> It works for me. Please show your `dmesg` output after running `insmod`

Oh I forget to rename the PROCNAME. After doing that it works fine. Thanks!

**Comment by carloslack** [comment]
> same problem...

rename your Makefile `PROCNAME`

**Comment by carloslack** [comment]
Please, use ascii  a-z for the name, not numbers then try again

**Comment by carloslack** [comment]
no issues from the building I see, show you `dmesg` when loading the module.
remember you need to `kill` to activate the proc entry, after loading the module.
