### ISSUE TITLE
No password required for association, lack of security

### ISSUE THREAD

**Issue by doge-dog** [carloslack/KoviD#93]
Command：
./bdclient.sh openssl 192.168.11.128 7777

You can consider adding the secret parameter, and the connection can only be made if the match is successful.

**Comment by carloslack** [comment]
Thanks for the suggestion @doge-dog , I will check this possibility

**Comment by carloslack** [comment]
but first, notice that the connection happens after a certain sequence of port-knocking packets are received by  KoviD, only then the connection is accepted, but yes, it is not a password.

**Comment by doge-dog** [comment]
everyone can connect and get other people's shells by traversing global ip addresses.

**Comment by carloslack** [comment]
yes , you are right, I will try to come up with something to overcome that, in the meantime I am keeping his issue open of course so we can continue from here, thanks @doge-dog

**Comment by carloslack** [comment]
@doge-dog https://github.com/carloslack/KoviD/commit/898b9c6423b32220675c23c7f1fd4346bacdc135

**Comment by carloslack** [comment]
Closing this as its implemented since https://github.com/carloslack/KoviD/commits/v3.0.0

@doge-dog if you read this, have a look and let me know if you see issues
thanks
